version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: agenda
    versions:
    - 4.0.1
    - 4.1.0
  - dependency-name: ajv
    versions:
    - 7.2.1
    - 7.2.3
  - dependency-name: "@types/convict"
    versions:
    - 6.0.0
  - dependency-name: "@types/agenda"
    versions:
    - 3.0.2
  - dependency-name: fastify-swagger
    versions:
    - 4.0.0
