apiVersion: v1
kind: Service
metadata:
  name: tribeca-scheduler
  labels:
    name: tribeca-scheduler
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30702
      name: tcp
  selector:
    run: tribeca-scheduler
